In [30]:
import numpy as np
import pandas as pd

In [12]:
u=np.random.rand(1,5) 
v=np.random.rand(1,5) 
print(u)
print(v)

[[0.99233566 0.25949063 0.07967804 0.86293104 0.7371998 ]]
[[0.71805937 0.71898795 0.90594847 0.2720991  0.32166591]]


In [47]:
np.dot(u,np.transpose(v))

array([[1.44324555]])

In [29]:
matriz = np.ones((10,2))
matriz

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
matriz.shape

(10, 2)

In [38]:
vector_a = matriz[:,0]
vector_b = matriz[:,1]
print(vector_a)
print(vector_b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
vector_a.shape

(10,)

In [42]:
df = pd.DataFrame(matriz)
df.shape

(10, 2)

In [43]:
columna1 = df[0]
columna2 = df[1]
print(columna1)
print(columna2)

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    1.0
Name: 0, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    1.0
Name: 1, dtype: float64


In [44]:
columna1.shape

(10,)

In [17]:
a = np.ones(10)
b = np.ones(10)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
a.shape

(10,)

In [18]:
np.dot(a,b)

10.0

In [13]:
np.dot(a,np.transpose(b))

10.0

In [15]:
np.linalg.norm(a)

3.1622776601683795

In [25]:
def verificar_ortogonalidad(u,v,tol = 10^-8):
    if np.linalg.norm(u) <= tol or np.linalg.norm(v) <= tol:
        resultado = 1
    elif ((np.dot(u,v))/(np.linalg.norm(u)*np.linalg.norm(v))) <= tol:
        resultado = 1
    else:
        resultado = 0
    return resultado

In [26]:
verificar_ortogonalidad(a,b)

0

In [39]:
verificar_ortogonalidad(vector_a,vector_b)

0

In [45]:
verificar_ortogonalidad(columna1,columna2)

0

In [51]:
ak = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
ak

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
ak@ak

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [55]:
np.dot(ak,np.transpose(ak))

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [52]:
sig = np.linalg.norm(ak, axis=0)
sig

array([6.70820393, 8.1240384 , 9.64365076])