In [1]:
import numpy as np
import pandas as pd

In [2]:
# Función para checar ortogonalidad de 2 vectores u, v
def verificar_ortogonalidad(u,v,tol = 10**-8):
    if np.linalg.norm(u) <= tol or np.linalg.norm(v) <= tol:
        resultado = 1
    elif ((np.dot(u,v))/(np.linalg.norm(u)*np.linalg.norm(v))) <= tol:
        resultado = 1
    else:
        resultado = 0
    return resultado

In [3]:
# Ejemplo de porque a la función anterior se le debe agregar que el producto punto de los vectotres u y v debe ser en valor absoluto

# Los siguientes 2 vectores son paraleros, pues uno es múltiplo del otro

vector1 = [i for i in range(10)]
vector2 = [-2*i for i in range(10)]

print(vector1)
print(vector2)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, -2, -4, -6, -8, -10, -12, -14, -16, -18]


In [4]:
# El producto punto de los dos vectores anteriores es -570, valor negativo, pero alejado del cero
np.dot(vector1,vector2)

-570

In [5]:
# No obstante si le aplicamos la función nos arroja que son ortogonales, 
verificar_ortogonalidad(vector1,vector2)

1

In [6]:
# Función con ajuste en el producto punto
# Función para checar ortogonalidad de 2 vectores u, v
def verificar_ortogonalidad(u,v,tol = 10**-8):
    if np.linalg.norm(u) <= tol or np.linalg.norm(v) <= tol:
        resultado = 1 # en vector nulo es ortogonal a cualquier vector, por ello si su norma es menor a la tolerancia, asignaremos que los vectores son ortogonales
    elif (np.abs(np.dot(u,v))/(np.linalg.norm(u)*np.linalg.norm(v))) <= tol:
        resultado = 1
    else:
        resultado = 0
    return resultado

In [7]:
# El resultado regresa cero, pues no son ortogonales
verificar_ortogonalidad(vector1,vector2)

0

In [8]:
def signo(x):
    if x<0:
        sig = -1
    else:
        sig = 1
    return sig

In [9]:
# Matriz de datos a utilizar

In [10]:
np.random.seed(2020)
A = np.random.randn(9, 6)
A

array([[-1.76884571,  0.07555227, -1.1306297 , -0.65143017, -0.89311563,
        -1.27410098],
       [-0.06115443,  0.06451384,  0.41011295, -0.57288249, -0.80133362,
         1.31203519],
       [ 1.27469887, -1.2143576 ,  0.31371941, -1.44482142, -0.3689613 ,
        -0.76922658],
       [ 0.3926161 ,  0.05729383,  2.08997884,  0.04197131, -0.04834072,
        -0.51315392],
       [-0.08458928, -1.21545008, -1.41293073, -1.48691055,  0.38222486,
         0.937673  ],
       [ 1.77267804,  0.87882801,  0.33171912, -0.30603567,  1.24026615,
        -0.21562684],
       [ 0.15592948,  0.09805553,  0.83209585,  2.04520542, -0.31681392,
        -1.31283291],
       [-1.75445746,  0.10209408, -1.36150208,  0.48178488, -0.20832874,
        -0.09186351],
       [ 0.70268816,  0.10365506,  0.62123638,  0.95411497,  2.03781352,
        -0.48445122]])

In [11]:
#dimensiones de A
n = A.shape[1] #numero de columnas
m = A.shape[0] #numero de filas
nmax =n*(n-1)/2
    
    #inicializa valores del ciclo
ak = A
vk = np.identity(n, dtype = float) 
sig = ''
uk = ak
num_col_ortogonal = 0
k = 0
stop = False

    
print(n)
print(m)
print(nmax)

6
9
15.0


In [12]:
maxsweep = 1
TOL = 10^-8

## Primera iteración

In [13]:
i = 0
j = 1

In [14]:
# columnas  a utilizar
col_i = ak[:,i]
col_j = ak[:,j]

print(col_i)
print(col_j)

[-1.76884571 -0.06115443  1.27469887  0.3926161  -0.08458928  1.77267804
  0.15592948 -1.75445746  0.70268816]
[ 0.07555227  0.06451384 -1.2143576   0.05729383 -1.21545008  0.87882801
  0.09805553  0.10209408  0.10365506]


In [15]:
# checar ortogonalidad
ort = verificar_ortogonalidad(col_i,col_j,TOL)
ort

0

In [16]:
#calcula coeficientes 
a = np.dot(col_i,col_i)
b = np.dot(col_j,col_j)
c = np.dot(col_i,col_j)

print(a)
print(b)
print(c)

11.657308047401893
3.768257188844304
-0.09333103452132008


In [17]:
#calcula la rotacion givens que diagonaliza
epsilon = (b-a)/(2*c)
t = signo(epsilon)/(abs(epsilon)+np.sqrt(1+epsilon**2))
cs = 1/np.sqrt(1+t**2)
sn = cs*t

print(epsilon)
print(t)
print(cs)
print(sn)

42.26381341972296
0.011828796299667356
0.9999300471298412
0.011827968841415671


In [18]:
#actualiza las columnas de la matriz ak
temp1 = ak[:,i].copy()
ak[:,i] = cs*temp1-sn*ak[:,j]                    
ak[:,j] = sn*temp1+cs*ak[:,j]

print(temp1)
print(ak[:,i])
print(ak[:,j])

[-1.76884571 -0.06115443  1.27469887  0.3926161  -0.08458928  1.77267804
  0.15592948 -1.75445746  0.70268816]
[-1.7696156  -0.06191322  1.28897309  0.39191097 -0.07020706  1.76215929
  0.15475878 -1.7555423   0.70141298]
[ 0.05462513  0.063786   -1.19919556  0.06193368 -1.21636558  0.89973371
  0.099893    0.08133527  0.11195918]


In [19]:
#actualiza las columnas de la matriz vk
temp2 = vk[:,i].copy() 
vk[:,i] = cs*temp2-sn*vk[:,j]
vk[:,j] = sn*temp2+cs*vk[:,j]             

print(temp2)
print(vk[:,i])
print(vk[:,j])

[1. 0. 0. 0. 0. 0.]
[ 0.99993005 -0.01182797  0.          0.          0.          0.        ]
[0.01182797 0.99993005 0.         0.         0.         0.        ]


In [20]:
#Obtener sigma
sig = np.linalg.norm(ak, axis=0)
sig

array([3.41444169, 1.94091556, 3.30928459, 3.23600126, 2.74937669,
       2.66311732])

## Segunda iteración

In [21]:
i = 1
j = 2

In [22]:
# columnas  a utilizar
col_i = ak[:,i]
col_j = ak[:,j]

print(col_i)
print(col_j)

[ 0.05462513  0.063786   -1.19919556  0.06193368 -1.21636558  0.89973371
  0.099893    0.08133527  0.11195918]
[-1.1306297   0.41011295  0.31371941  2.08997884 -1.41293073  0.33171912
  0.83209585 -1.36150208  0.62123638]


In [23]:
# checar ortogonalidad
ort = verificar_ortogonalidad(col_i,col_j,TOL)
ort

0

In [24]:
#calcula coeficientes 
a = np.dot(col_i,col_i)
b = np.dot(col_j,col_j)
c = np.dot(col_i,col_j)

print(a)
print(b)
print(c)

3.767153195048514
10.951364468694926
1.7766625299023269


In [25]:
#calcula la rotacion givens que diagonaliza
epsilon = (b-a)/(2*c)
t = signo(epsilon)/(abs(epsilon)+np.sqrt(1+epsilon**2))
cs = 1/np.sqrt(1+t**2)
sn = cs*t

print(epsilon)
print(t)
print(cs)
print(sn)

2.0218277677194463
0.2337846817765657
0.9737438660317072
0.22764639985210547


In [26]:
#actualiza las columnas de la matriz ak
temp1 = ak[:,i].copy()
ak[:,i] = cs*temp1-sn*ak[:,j]                    
ak[:,j] = sn*temp1+cs*ak[:,j]

print(temp1)
print(ak[:,i])
print(ak[:,j])

[ 0.05462513  0.063786   -1.19919556  0.06193368 -1.21636558  0.89973371
  0.099893    0.08133527  0.11195918]
[ 0.31057467 -0.03124951 -1.23912641 -0.41546862 -0.86277992  0.80059552
 -0.09215343  0.38914077 -0.03240266]
[-1.08850852  0.41386562  0.0324898   2.04920305 -1.65273388  0.5278306
  0.83298851 -1.30723862  0.63041222]


In [27]:
#actualiza las columnas de la matriz vk
temp2 = vk[:,i].copy()
vk[:,i] = cs*temp2-sn*vk[:,j]
vk[:,j] = sn*temp2+cs*vk[:,j]             

print(temp2)
print(vk[:,i])
print(vk[:,j])

[0.01182797 0.99993005 0.         0.         0.         0.        ]
[ 0.01151741  0.97367575 -0.2276464   0.          0.          0.        ]
[0.00269259 0.22763048 0.97374387 0.         0.         0.        ]


In [28]:
#Obtener sigma
sig = np.linalg.norm(ak, axis=0)
sig

array([3.41444169, 1.83079128, 3.3714568 , 3.23600126, 2.74937669,
       2.66311732])

## Tercera iteración

In [29]:
i = 2
j = 3

In [30]:
# columnas  a utilizar
col_i = ak[:,i]
col_j = ak[:,j]

print(col_i)
print(col_j)

[-1.08850852  0.41386562  0.0324898   2.04920305 -1.65273388  0.5278306
  0.83298851 -1.30723862  0.63041222]
[-0.65143017 -0.57288249 -1.44482142  0.04197131 -1.48691055 -0.30603567
  2.04520542  0.48178488  0.95411497]


In [31]:
# checar ortogonalidad
ort = verificar_ortogonalidad(col_i,col_j,TOL)
ort

0

In [32]:
#calcula coeficientes 
a = np.dot(col_i,col_i)
b = np.dot(col_j,col_j)
c = np.dot(col_i,col_j)

print(a)
print(b)
print(c)

11.366720952872488
10.471704181649763
4.482299702560203


In [33]:
#calcula la rotacion givens que diagonaliza
epsilon = (b-a)/(2*c)
t = signo(epsilon)/(abs(epsilon)+np.sqrt(1+epsilon**2))
cs = 1/np.sqrt(1+t**2)
sn = cs*t

print(epsilon)
print(t)
print(cs)
print(sn)

-0.09983901463700748
-0.9051325415991323
0.7413990540902834
-0.6710644101679307


In [34]:
#actualiza las columnas de la matriz ak
temp1 = ak[:,i].copy()
ak[:,i] = cs*temp1-sn*ak[:,j]                    
ak[:,j] = sn*temp1+cs*ak[:,j]

print(temp1)
print(ak[:,i])
print(ak[:,j])

[-1.08850852  0.41386562  0.0324898   2.04920305 -1.65273388  0.5278306
  0.83298851 -1.30723862  0.63041222]
[-1.24417079 -0.07760147 -0.94548033  1.54744266 -2.22314809  0.18596347
  1.99004146 -0.64587679  1.10765962]
[ 0.24748962 -0.70246503 -1.09299198 -1.34402975  0.00669681 -0.58110288
  0.95732442  1.23443616  0.28433273]


In [35]:
#actualiza las columnas de la matriz vk
temp2 = vk[:,i].copy() 
vk[:,i] = cs*temp2-sn*vk[:,j]
vk[:,j] = sn*temp2+cs*vk[:,j]             

print(temp2)
print(vk[:,i])
print(vk[:,j])

[0.00269259 0.22763048 0.97374387 0.         0.         0.        ]
[0.00199629 0.16876502 0.72193278 0.67106441 0.         0.        ]
[-0.0018069  -0.15275471 -0.65344485  0.74139905  0.          0.        ]


In [36]:
#Obtener sigma
sig = np.linalg.norm(ak, axis=0)
sig

array([3.41444169, 1.83079128, 3.92731413, 2.53271176, 2.74937669,
       2.66311732])

In [37]:
# Prueba de temp, se actualiza al mismo tiempo que vk

In [100]:
temp = vk[:,i] 

In [38]:
print(temp)
print(vk[:i])

[ 0.00188058  0.15897207  0.66148021 -0.69658666  0.          0.        ]
[[ 0.99993005  0.01151676  0.00188058  0.00130999  0.          0.        ]
 [-0.01182797  0.97355234  0.15897207  0.11073782  0.          0.        ]]


In [47]:
vk[:,i] = 10* vk[:,i]

In [48]:
print(temp)
print(vk[:,i])

[   1.8805798   158.97207008  661.48020658 -696.58666329    0.
    0.        ]
[   1.8805798   158.97207008  661.48020658 -696.58666329    0.
    0.        ]


In [ ]:
# Prueba de temp, se actualiza al mismo tiempo que vk

In [53]:
temp = vk[:,i].copy()
temp

array([   1.8805798 ,  158.97207008,  661.48020658, -696.58666329,
          0.        ,    0.        ])

In [55]:
print(temp)
print(vk[:,i])

[   1.8805798   158.97207008  661.48020658 -696.58666329    0.
    0.        ]
[   1.8805798   158.97207008  661.48020658 -696.58666329    0.
    0.        ]


In [61]:
vk[:,i] = 10* vk[:,i]

In [62]:
print(temp)
print(vk[:,i])

[   1.8805798   158.97207008  661.48020658 -696.58666329    0.
    0.        ]
[   1880.57980466  158972.07007911  661480.20658413 -696586.66328578
       0.               0.        ]
